services:
  - type: web
    name: stock-snapshot-api
    env: node
    buildCommand: |
      chmod +x start.sh
      ./start.sh
      npm install
      npm run build
    startCommand: node dist/index.js
    plan: free
